### ISSUE TITLE
Document architecture for storing document views specifically and storage module in general

### ISSUE THREAD

**Issue by cafca** [p2panda/aquadoggo#125]

**Comment by sandreae** [comment]
I documented this a bit more for entry and log here: https://github.com/p2panda/aquadoggo/pull/126

**Comment by sandreae** [comment]
Also beefed up the docs for `OperationStore`

**Comment by sandreae** [comment]
I've reflected a little more on the reason these design decisions were needed, and I think there are some interesting conclusions. It is a slightly different story at each level of the p2panda "data stack" and so maybe we can make some tweaks here and there which will ultimately simplify the flow between storage and memory representations of all our types.

# Thoughts on our data types

## Logs
- these simply don't exist in `p2panda-rs` as a stand-alone thing, that's why we need a `StorageLog` in `aquadoggo` and the `AsStorageLog` trait to spell out what methods we expect it to have. I think this is fine though. We could choose to have a log struct in the main lib, but I don't think it matters either way. Having this trait pattern means other node implementations can have their own idea of how a log is represented.

## Entries
- we have `Entry` & `EntrySigned` in `p2panda-rs`. In `aquadoggo` we have another struct wrapping fields from both of these with an encoded operation. We aren't handling payload deletion yet, so we are enforcing here that all entries have an accompanying operation. This is part of the reason `StorageEntry` came to be, and the accompanying `AsStorageEntry` traits. Again, having the traits means that different node implementations could use their own specialised data types with our `StorageProvider`. 

## Operations
- We have `Operation` and `OperationWithMeta` in `p2panda-rs. They have their own traits as many methods overlap and it was a nice way of staying DRY. In  the storage provider we have `StorageOperation` and it's accompanying `AsStorageOperation` traits which wraps an operation with it's `Author`, `OperationId` and `DocumentId`. This is almost (exactly?) the same as `OperationWithMeta` and it's accompanying traits. We can definitely do some nice refactoring here. More on that below.

## Documents, DocumentViews, Schemas etc...
- Here I think the paradigm changes a little. Documents, DocumentViews and Schemas (and whatever comes next) are all quite "high-level" data. They are relatively stand alone, and they were designed for a specific purpose (representing data and sticking it in storage/reading it). From here, I think we already don't need any specialised storage types or wrappers. I've just refactored the `DocumentStore` PR to just use `Document` and `DocumentView` in all it's param args/return values and it makes a lot of sense. I think in the case where an implementer wants to have a node that materialises entries & operations in a completely different way they would implement their own custom storage solution.

# Take-away's

- it's nice to split our data types into:
  - "high-level" (Document, DocumentView, Schema et al)
    - a part/result of the materialisation process
    - not integral to log or operation graph validity
    - not transported between nodes during replication
  -  and "low-level" (Entry, Operation)
    - core data types
    - integral for validating logs and building document graphs
    - transported via replication
- our lower level "core" data types currently need some wrapping (log, entry, operation), likely because they were designed to be lean, maybe this can be changed as we go forward by introducing intermediary structs (refining what we have) in `p2panda-rs`. It would involve some refactoring, maybe defining their methods with traits which we then re-use in `StorageProvider`
- our "higher-level" structs can be re-used in the storage provider without wrapping.
- maybe we could have some seperation in `StorageProvider` between these lower level and higher level data types (so you could de-couple them, or even just use the low level one for a lean node).

**Comment by sandreae** [comment]
I know that looks like a big rant, but I'm not suggesting a hugely different direction, just some things to think about as we go forward. I think it helps understand the current architecture of the storage stuff in general, and also the idiosyncrasies present in `aquadoggo` vs `p2panda-rs`.

**Comment by sandreae** [comment]
This issue is maybe stale now as the storage traits have changed quite a lot and are quite well documented now.
