### ISSUE TITLE
High idle CPU utilization

### ISSUE THREAD

**Issue by cafca** [p2panda/aquadoggo#127]
With idle workers, aquadoggo on `development` uses ~400% CPU for me.

**Comment by adzialocha** [comment]
I can imagine this is due to our loop implementation where every cycle wakes the runtime even when the queue is empty (`loop` and `yield_now`). We added this to not starve the runtime with an infinite loop but it's not Rust async best-practice.

Probably this can be solved with a scheduler logic (future stream) which only wakes the runtime when there is a task waiting in the queue, maybe even combined with a round robin strategy checking that all queues are equally considered.

**Comment by adzialocha** [comment]
Enjoyed reading this article which probably solved a very similar issue of scheduling: https://smb374.github.io/an-adventure-in-rust-s-async-runtime-model.html
